### ISSUE TITLE
Coupling EP+ and Python

### ISSUE THREAD

**Issue by mehrdadxyz** [JasonGlazer/Drumlin#3]
Dear Jason,

I'm looking for a way to couple EP+ and Python. I found Drumlin interesting since its excel base and can be manipulated using Python.
I want to use python as a control processor to implement real-time control of an HVAC unit simulated in EP+. So I need to manipulate some of the HVAC unit parameters in each time step.

Do you think Drumlin can help me? if not, What's your suggestion?

**Comment by JasonGlazer** [comment]
No I don't think Drumlin can help you. EnergyPlus has a way to manipulate parameters each timestep called EMS but it uses its own programming language that is not Python. See the EMSApplicationGuide.pdf document that comes with EnergyPlus as well as the InputOutputReference under the group called Energy Management Systems for more details. The EnergyPlus development team is actually working on a Python version of this but it is not ready yet and probably won't be for at least until version 9.3 (six months) or 9.4 (one year).

The term "real-time" implies that you want EnergyPlus to interface with another program each timestep. For that, you might want to look in the InputOutputReference under ExternalInterface it talks about how to use EnergyPlus with a Functional Mockup Interface.

For more questions like this you might want to use UnmetHours.com or the EnergyPlus helpdesk at http://energyplus.helpserve.com/
